import { Output } from "@mui/icons-material"

const buttonContent = {
 //Update ButtonValues also when updating this 
 
 //ButtonValue Provides the data for backend json




 //driver, comment

    "Assign":{
        "Variable Type": {"options":["String","Int","List","Dict","Float","Tuple","Boolean","Bytes","Set","Frozenset",],"type":"select", "value":""},
        "Variable Name":{"value":""},
        "Variable Value":{"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "OpenBrowser":{
        "Browser Type": {"options":["Chrome","Edge"],"type":"select", "value":""},
        "Enter URL": {"value":"", "type":"string"},
        "Browser Width": {"options":["Default","Full Width"],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Openbroweser_V1":{
        "Browser Type": {"options":["Chrome","Edge"],"type":"select", "value":""},
        "Enter URL": {"value":""},
        "Browser Width": {"options":["Default","Full Width"],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "Description":{"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "OpenBrowserProfile":{
        "Browser Type": {"options":["Chrome","Edge"],"type":"select", "value":""},
        "Enter URL": {"value":""},
        "Browser Width": {"options":["Default","Full Width"],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "Description":{"value":""},
        "Enter User Data DIR":{"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Openbrowser_with_extension":{
        "Browser Type": {"options":["Chrome","Edge"],"type":"select", "value":""},
        "Extension Path":{"value":""},
        "Enter URL": {"value":""},
        "Browser Width": {"options":["Default","Full Width"],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "Description":{"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Browser_Debugging":{
        "Browser Type": {"options":["Chrome","Edge"],"type":"select", "value":""},
        "Enter URL": {"value":""},
        "Browser Width": {"options":["Default","Full Width"],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "Description":{"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
        "Get_Text":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Enter Text": {"value":""},
        "Delay (in Seconds)": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "TypeInto":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Text": {"value":""},
        "Enter Send Key Value": {"value":""},
        "Delay (in Seconds)":  {"value":""},
        "driver": "driver",
        "Description":  {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Click":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Text": {"value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "MouseHover":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Text": {"value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "MouseHover":{
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Comment": "",
        "Breakpoint": "",
    },
    "Hightlight":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Text": {"value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "WindowHandle":{
        "index": {"value":""},
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "ElementWait":{
        "driver": "driver",
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Enter Value": {"value":""},
        "Enter Timeout":{"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "ElementExist":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Text": {"value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "BrowserClose":{
        "Description": {"value":""}
    },
    "GoBack":{
        "Description": {"value":""}
    },
    "Maximize":{
        "Description": {"value":""}
    },
    "DropdownSelection":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Text": {"value":""},
        "Enter Send Key Value":{"value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "CheckBox":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Value": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "FindElements":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Value": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },  
    "Iframe":{
        "Index": {"value":""},
        "Description": {"value":""},
    },
    "OpenNewTab":{
        "Enter URL": {"value":""},
        "Description": {"value":""},
    },
    "GetUrl":{
        "Enter URL": {"value":""},
        "Description": {"value":""},
    },
    "EmptyElement":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Xpath": {"value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "SelectElement":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Xpath": {"value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "tabletodt":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Xpath": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "tabletodtv1":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Enter Xpath": {"value":""},
        "Multiple Page": {"options":["True", "False"],"type":"select", "value":""},
        "Next Button xpath":{"value":""},
        "Modify Column":{"value":""},
        "Disable Element":{"value":""},
        "Attribute Name":{"value":""},
        "Attribute Value":{"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Keyboardhotkey":{
        "Value": {"value":""},
        "Description": {"value":""},
    },

   "Stringcaseconversion":{
        "Input String": {"value":""},
        "Case Conversion Type": {"options":["X Path Selector"],"type":"select", "value":""},
        "Output Variable": {"options":["Upper","Lower","Capitalize","Swapcase","Title","Casefold",]},        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Dropdown":{
        "Inner Html": {"value":"","type":"long text",},
        "Outer Html": {"value":"","type":"long text",},
        "Value": {"value":""}, 
        "Name": {"value":""},
        "Id": {"value":""},
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Getattribute":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Value": {"value":""},
        "Attribute Name": {"options":["innerHTML","outerHTML","value","name","id","Disabled"],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Modifyattribute":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Value": {"value":""},
        "Attribute Name": {"options":["innerHTML","outerHTML","value","name","id","Disabled"],"type":"select", "value":""},
        "Modify Attribute":{"options":["Add Attribute","Remove Attribute"],"type":"select", "value":""},
        "driver": "driver",
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Hreffiledownload":{
        "URL": {"value":""},
        "Save Path":{"value":""},
        "Description": {"value":""},
    },
    "Checkboxactiveinactive":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Value": {"value":""},
        "Checkin/Checkout":{"options":["Checkin","Checkout"],"type":"select", "value":""},
        "Output Message": {"value":""},
        "Delay (in Seconds)": {"value":""},
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
        "driver": "driver",
    },
    "Dropdownchild":{
        "Selector Type": {"options":["X Path","ID","Name","Class","Tag Name"],"type":"select", "value":""},
        "Selector Tool": {"options":["X Path Selector"],"type":"select", "value":""},
        "Value": {"value":""},
        "Output Message": {"value":""},
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
        "driver": "driver",
    },
    "Chromedriverdownloader":{
        "Description": {"value":""},
    },
    "Dashboardstatus":{
        "Task Id": {"value":""},
        "Status":{"options":["Start","Completed","Failed"],"type":"select", "value":""},
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
        "driver": "driver",
    },  
    "Add":{
        "Variable1":{"value":""},
        "Variable2":{"value":""},
        "Variable3":{"value":""},
        "Variable4":{"value":""},
        "Description": {"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Variable":{
        "Variable Type": "",
        "Variable Name":{"value":""},
        "Variable Value":{"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Constant":{
        "Constant Type": "",
        "Constant Value":{"value":""},
        "Comment": "",
        "Breakpoint": "",
    },
    "Createfile":{
        "Path File":{"value":""},
        "File Name":{"value":""},
        "Description": {"value":""},
    },
    "Textfileread":{
        "File Path": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
    },
    "Openfile":{
        "Path": {"value":""},
        "Description": {"value":""},
    },
    "Msgbox":{
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
    },
    "Msgboxtimer":{
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Delay (in Seconds)": {"value":""},
        "Description": {"value":""},
    },
    "Mfacode":{
        "Tokens": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
    },
    "Copyfile":{
        "Source Path": {"value":""},
        "Destination Path": {"value":""},
        "Description": {"value":""},
    },
    "Movefile":{
        "Source Path": {"value":""},
        "Destination Path": {"value":""},
        "Description": {"value":""},
    },
    "Clickcoordinate":{
        "X Coordinate": {"value":""},
        "Y Coordinate": {"value":""},
        "Description": {"value":""},
    },
    "Clickcoordinatevsimulate":{
        "X Coordinate": {"value":""},
        "Y Coordinate": {"value":""},
        "Description": {"value":""},
    },
    "Hovercoordinate":{
        "X Coordinate": {"value":""},
        "Y Coordinate": {"value":""},
        "Description": {"value":""},
    },
    "Typecoordinate":{
        "X Coordinate": {"value":""},
        "Y Coordinate": {"value":""},
        "Send Keys": {"value":""},
        "Description": {"value":""},
    },
    "Doubleclickcoordinate":{
        "X Coordinate": {"value":""},
        "Y Coordinate": {"value":""},
        "Description": {"value":""},
    },
    "Fileexist":{
        "File Path": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
    },
    "Minactivewindow":{
        "Description": {"value":""},
    },
    "Movepreviouswindow":{
        "Description": {"value":""},
    },
    "Datetime":{
        "Expression": {"value":""},
        "Type":{"value":""},
        "Value": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
    },
    "Getlastestfile":{
        "File Path": {"value":""},
        "File Type":{"options":[".pdf",".xlsx",".csv",".docx",".dox",".png","jpg",".jpeg"],"type":"select", "value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
    },
    "writetextfile":{
        "File Path": {"value":""},
        "Content": {"value":""},
        "Description": {"value":""},
    },
    "Keyboardactivity":{
        "Value": {"value":""},
        "Description": {"value":""},
    }, 
    "Getlistoffiles":{
        "Folder Path": {"value":""},
        "Output Variable": {"options":[],"type":"select", "value":""},
        "Description": {"value":""},
    },
    "Renamefile":{
        "Source Path": {"value":""},
        "Destination Path": {"value":""},
        "Description": {"value":""},
    }
    

}


export default buttonContent
