const buttonValue = {

    "Assign":{
        "Variable Type":"",
        "Variable Name":"",
        "Variable Value":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "OpenBrowser":{
        "Browser Type":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Openbroweser_V1":{
        "Browser Type":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "OpenBrowserProfile":{
        "Browser Type":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Enter User Data DIR":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Openbrowser_with_extension":{
        "Browser Type":"",
        "Extension Path":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Browser_Debugging":{
        "Browser Type":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
        "Get_Text":{
        "Selector Type":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "Output Variable":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "TypeInto":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Enter Send Key Value":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Click":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "MouseHover":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "MouseHover":{
        "Delay (in Seconds)":"",
        "driver":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Hightlight":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "WindowHandle":{
        "index":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "ElementWait":{
        "driver":"",
        "Selector Type":"",
        "Enter Value":"",
        "Enter Timeout":"",
        "Output Variable":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "ElementExist":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Output Variable":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "BrowserClose":{
        "Description": {"value":""}
    },
    "GoBack":{
        "Description": {"value":""}
    },
    "Maximize":{
        "Description": {"value":""}
    },
    "DropdownSelection":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Enter Send Key Value":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "CheckBox":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Output Variable":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "FindElements":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Output Variable":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },  
    "Iframe":{
        "Index":"",
        "Description":"",
    },
    "OpenNewTab":{
        "Enter URL":"",
        "Description":"",
    },
    "GetUrl":{
        "Enter URL":"",
        "Description":"",
    },
    "EmptyElement":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Xpath":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "SelectElement":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Xpath":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "tabletodt":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Xpath":"",
        "Output Variable":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "tabletodtv1":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Xpath":"",
        "Multiple Page":"",
        "Next Button xpath":"",
        "Modify Column":"",
        "Disable Element":"",
        "Attribute Name":"",
        "Attribute Value":"",
        "Output Variable":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Keyboardhotkey":{
        "Value":"",
        "Description":"",
    },

   "Stringcaseconversion":{
        "Input String":"",
        "Case Conversion Type":"",
        "Output Variable":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Dropdown":{
        "Inner Html":"",
        "Outer Html":"",
        "Value":"", 
        "Name":"",
        "Id":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Getattribute":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Attribute Name":"",
        "Delay (in Seconds)":"",
        "Output Variable":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Modifyattribute":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Attribute Name":"",
        "Modify Attribute":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Hreffiledownload":{
        "URL":"",
        "Save Path":"",
        "Description":"",
    },
    "Checkboxactiveinactive":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Checkin/Checkout":"",
        "Output Message":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
        "driver":"",
    },
    "Dropdownchild":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Output Message":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
        "driver":"",
    },
    "Chromedriverdownloader":{
        "Description":"",
    },
    "Dashboardstatus":{
        "Task Id":"",
        "Status":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
        "driver":"",
    },
    "Variable":{
        "Variable Type": "",
        "Variable Name":"",
        "Variable Value":"",
        "Comment": "",
        "Breakpoint": "",
    }
    ,
    "Constant":{
        "Constant Type":"",
        "Constant Value":"",
        "Comment": "",
        "Breakpoint": "",
    }

}


export default buttonValue
