const buttonValue = {

   
    "Assign":{
        "Variable Type":"",
        "Variable Name":"",
        "Variable Value":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "OpenBrowser":{
        "Browser Type":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Openbroweser_V1":{
        "Browser Type":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "OpenBrowserProfile":{
        "Browser Type":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Description":{"value":""},
        "Enter User Data DIR":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Openbrowser_with_extension":{
        "Browser Type":"",
        "Extension Path":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Browser_Debugging":{
        "Browser Type":"",
        "Enter URL":"",
        "Browser Width":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
        "Get_Text":{
        "Selector Type":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "Output Variable":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "TypeInto":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Enter Send Key Value":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Click":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "MouseHover":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "TimeDelay":{
        "Delay (in Seconds)":"",
        "driver":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Hightlight":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "WindowHandle":{
        "index":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "ElementWait":{
        "driver":"",
        "Selector Type":"",
        "Enter Value":"",
        "Enter Timeout":"",
        "Output Variable":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "ElementExist":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Output Variable":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "BrowserClose":{
        "Description":"",
    },
    "GoBack":{
        "Description":"",
    },
    "Maximize":{
        "Description":"",
    },
    "DropdownSelection":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Text":"",
        "Enter Send Key Value":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "CheckBox":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Output Variable":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "FindElements":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Output Variable":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },  
    "Iframe":{
        "Index":"",
        "Description":"",
    },
    "OpenNewTab":{
        "Enter URL":"",
        "Description":"",
    },
    "GetUrl":{
        "Enter URL":"",
        "Description":"",
    },
    "EmptyElement":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Xpath":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "SelectElement":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Xpath":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "tabletodt":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Xpath":"",
        "Output Variable":"",
        "Delay (in Seconds)":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "tabletodtv1":{
        "Selector Type":"",
        "Selector Tool":"",
        "Enter Xpath":"",
        "Multiple Page":"",
        "Next Button xpath":"",
        "Modify Column":"",
        "Disable Element":"",
        "Attribute Name":"",
        "Attribute Value":"",
        "Output Variable":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Keyboardhotkey":{
        "Value":"",
        "Description":"",
    },

   "Stringcaseconversion":{
        "Input String":"",
        "Case Conversion Type":"",
        "Output Variable":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Dropdown":{
        "Inner Html":"",
        "Outer Html":"",
        "Value":"",
        "Name":"",
        "Id":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Getattribute":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Attribute Name":"",
        "Delay (in Seconds)":"",
        "Output Variable":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Modifyattribute":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Attribute Name":"",
        "Modify Attribute":"",
        "driver":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Hreffiledownload":{
        "URL":"",
        "Save Path":{"value":""},
        "Description":"",
    },
    "Checkboxactiveinactive":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Checkin/Checkout":"",
        "Output Message":"",
        "Delay (in Seconds)":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
        "driver":"",
    },
    "Dropdownchild":{
        "Selector Type":"",
        "Selector Tool":"",
        "Value":"",
        "Output Message":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
        "driver":"",
    },
    "Chromedriverdownloader":{
        "Description":"",
    },
    "Dashboardstatus":{
        "Task Id":"",
        "Status":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
        "driver":"",
    },  
    "Add":{
        "Variable1":"",
        "Variable2":"",
        "Variable3":"",
        "Variable4":"",
        "Description":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Variable":{
        "Variable Type":"",
        "Variable Name":"",
        "Variable Value":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Constant":{
        "Constant Type":"",
        "Constant Value":"",
        "Comment":"",
        "Breakpoint":"",
    },
    "Createfile":{
        "Path File":"",
        "File Name":"",
        "Description":"",
    },
    "Textfileread":{
        "File Path":"",
        "Output Variable":"",
        "Description":"",
    },
    "Openfile":{
        "Path":"",
        "Description":"",
    },
    "Msgbox":{
        "Output Variable":"",
        "Description":"",
    },
    "Msgboxtimer":{
        "Output Variable":"",
        "Delay (in Seconds)":"",
        "Description":"",
    },
    "Mfacode":{
        "Tokens":"",
        "Output Variable":"",
        "Description":"",
    },
    "Copyfile":{
        "Source Path":"",
        "Destination Path":"",
        "Description":"",
    },
    "Movefile":{
        "Source Path":"",
        "Destination Path":"",
        "Description":"",
    },
    "Clickcoordinate":{
        "X Coordinate":"",
        "Y Coordinate":"",
        "Description":"",
    },
    "Clickcoordinatesimulate":{
        "X Coordinate":"",
        "Y Coordinate":"",
        "Description":"",
    },
    "Hovercoordinate":{
        "X Coordinate":"",
        "Y Coordinate":"",
        "Description":"",
    },
    "Typecoordinate":{
        "X Coordinate":"",
        "Y Coordinate":"",
        "Send Keys":"",
        "Description":"",
    },
    "Doubleclickcoordinate":{
        "X Coordinate":"",
        "Y Coordinate":"",
        "Description":"",
    },
    "Fileexist":{
        "File Path":"",
        "Output Variable":"",
        "Description":"",
    },
    "Minactivewindow":{
        "Description":"",
    },
    "Maxactivewindow":{
        "Description":"",
    },
    "Movepreviouswindow":{
        "Description":"",
    },
    "Datetime":{
        "Expression":"",
        "Type":{"value":""},
        "Value":"",
        "Output Variable":"",
        "Description":"",
    },
    "Getlastestfile":{
        "File Path":"",
        "File Type":"",
        "Output Variable":"",
        "Description":"",
    },
    "writetextfile":{
        "File Path":"",
        "Content":"",
        "Description":"",
    },
    "Keyboardactivity":{
        "Value":"",
        "Description":"",
    }, 
    "Getlistoffiles":{
        "Folder Path":"",
        "Output Variable":"",
        "Description":"",
    },
    "Renamefile":{
        "Source Path":"",
        "Destination Path":"",
        "Description":"",
    },
    "Killprocess":{
        "Process Name":"",
        "Description":"",
    },
    "Excelconfig":{
        "Excel Path":"",
        "Output Variable":"",
        "Description":"",
    },
    "Getfileline":{
        "File Path":"",
        "Line":"",
        "Output Variable":"",
        "Description":"",
    },
    "Excelreadrange":{
        "File Path":"",
        "Sheet Name":"",
        "Read Range":"",
        "Output Variable":"",
        "Description":"",
    },
    "Excelwriterange":{
        "File Path":"",
        "Data":{"value":""},
        "Sheet Name":"",
        "Start Cell":"",
        "Description":"",
    },
    "Excelwritecell":{
        "File Path":"",
        "Sheet Name":"",
        "Write Cell":"",
        "Write Value":"",
        "Description":"",
    },
    "Readexcelsheet":{
        "File Path":"",
        "Sheet Name":"",
        "Output Variable":"",
        "Description":"",
    },
    "Excelappendrow":{
        "Excel Path":"",
        "Data":"",
        "Sheet Name":"",
        "Description":"",
    },
    "Addsheetintoexcel":{
        "Data":"",
        "Existing File Path":"",
        "New Sheet Name":"",
        "Description":"",
    },
    "Excelunhiderows":{
        "Excel Path":"",
        "Description":"",
    },
    "Getcellnumberbyvalue":{
        "Excel Path":"",
        "Sheet Name":"",
        "Search String":"",
        "Cell Number":"",
        "Column Letter":"",
        "Row Number":"",
        "Description":"",
    },
    "Getsheetname":{
        "Excel Path":"",
        "Output Variable":"",
        "Description":"",
    },
    "Conver_dt_json":{
        "Input DataTable":"",
        "Output Variable":"",
        "Description":"",
    },
    "Excelrowcount":{
        "File Path":"",
        "Sheet Name":"",
        "Start Index":"",
        "Output Variable":"",
        "Description":"",
    },
    "Xlstoxlsx":{
        "XLS File Path":"",
        "XLSX File Path":"",
        "Description":"",
    },
    "Excelheadermodify":{
        "File Path":"",
        "Sheet Name":"",
        "New Header":"",
        "Customize header":"",
        "Description":"",
    },
    "Excelcolorcodefilter":{
        "File Path":"",
        "Sheet Name":"",
        "Column Index":"",
        "Color Code":"",
        "Output Variable":"",
        "Description":"",
    },
    "Excelwritecelldepricated":{
        "File Path":"",
        "Data":"",
        "Write Value":"",
        "Check Value":"",
        "Check Column Value":"",
        "Write Column":"",
        "Description":"",
    },
    "Excelreadcell":{
        "File Path":"",
        "Cell Ref":"",
        "Sheet Name":"",
        "Output Variable":"",
        "Description":"",
    },
    "Csvtoexcel":{
        "CSV File Path":"",
        "Excel File Path":"",
        "Description":"",
    },
    "Excelcheckboxcheck":{
        "File Path":"",
        "Sheet Name":"",
        "Cell Address":"",
        "Output Variable":"",
        "Description":"",
    }

}


export default buttonValue
